package buzzword;


public enum BuzzwordProperty {
    WORKSPACE_HEADING_LABEL,
    ROOT_BORDERPANE_ID,
    TOP_TOOLBAR_ID,
    SEGMENTED_BUTTON_BAR,
    FIRST_TOOLBAR_BUTTON,
    LAST_TOOLBAR_BUTTON,
    HELP_BUTTON,
    QUIT_BUTTON,
    PLAY_RESUME_BUTTON,
    NEXT_GAME_BUTTON,
    PREV_GAME_BUTTON,
    HEADING_LABEL;

}
